### PR TITLE
Document how to prepare a NodeJS container

### PR DESCRIPTION
**Pull request by aespinosa**

### CODE REVIEW

**Comment by crigor** [comment]
The docker_nodejs recipe failed for me.  
```
Parent directory /data/docker_nodejs/shared/config does not exist
```
Can you move /data/docker_nodejs/shared/config/config.json to /data/docker_apps/docker_nodejs/config/config.json?

We'll put all apps on /data/docker_apps. And there's no need for shared.

**Comment by crigor** [comment]
It should also point to /usr/src/app/config/config.json (add the config/ directory)

**Comment by aespinosa** [comment]
done with the directory changes.

**Comment by crigor** [comment]
Add an environment variable NODE_ENV with value of "production".

**Comment by aespinosa** [comment]
done

**Pull request merged**
